spring.application.name=taskManager
spring.data.mongodb.database=taskdb
spring.data.mongodb.uri=mongodb+srv://kushwahaakash1083_db_user:TaSk1083MaNaGeR@cluster0.otfjdvj.mongodb.net/?appName=Cluster0
server.port=${PORT:8080}

